# Generated by Django 3.2.8 on 2022-01-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UpgradeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('change_No', models.CharField(default='CHG0000036', max_length=25, null=True)),
                ('change_status', models.CharField(choices=[('Approved', 'Approved'), ('Not Approved', 'Not Approved'), ('Rejected', 'Rejected'), ('Incorrect Change Window', 'Incorrect Change Window')], default='Approved', editable=False, max_length=25, null=True)),
                ('device_Type', models.CharField(choices=[('IOS', 'IOS'), ('NXOS', 'NXOS'), ('IOSXR', 'IOSXR')], default='IOS', max_length=25, null=True)),
                ('device_IP', models.GenericIPAddressField(default='3.13.93.157', null=True)),
                ('device_Username', models.CharField(default='amar', max_length=25, null=True)),
                ('device_Password', models.CharField(default='cisco', max_length=150, null=True)),
                ('enable_Password', models.CharField(default='cisco', max_length=150, null=True)),
                ('tFTP_IP', models.GenericIPAddressField(default='3.19.131.3', null=True)),
                ('tFTP_Username', models.CharField(default='amar', max_length=25, null=True)),
                ('tFTP_Password', models.CharField(default='cisco', max_length=150, null=True)),
                ('image_Size_In_MB', models.IntegerField(default=1024)),
                ('image_Name', models.CharField(default='csr1000v.light.image.bin', max_length=40, null=True)),
                ('mD5_Value', models.CharField(default='c94df39614e265a4a3b7e7ad49db9607', max_length=40, null=True)),
                ('upgrade_status', models.CharField(choices=[('Successful', 'Successful'), ('Pending', 'Pending'), ('Cancelled', 'Cancelled'), ('Failed', 'Failed'), ('Completed with Issues', 'Completed with Issues')], default='Pending', editable=False, max_length=25, null=True)),
                ('date_created', models.DateTimeField(editable=False, null=True)),
                ('last_modified', models.DateTimeField(editable=False, null=True)),
                ('device_status', models.CharField(editable=False, max_length=100, null=True)),
                ('device_goahead', models.CharField(editable=False, max_length=50, null=True)),
                ('device_free_space_pre', models.IntegerField(editable=False, null=True)),
                ('device_precheck_result', models.CharField(editable=False, max_length=10000, null=True)),
                ('device_upgrade_cmds', models.CharField(editable=False, max_length=10000, null=True)),
                ('device_postcheck_result', models.CharField(editable=False, max_length=10000, null=True)),
                ('device_free_space_post', models.IntegerField(editable=False, null=True)),
                ('device_current_image', models.CharField(editable=False, max_length=50, null=True)),
                ('device_generated_md5', models.CharField(editable=False, max_length=50, null=True)),
                ('tftp_image_size', models.IntegerField(editable=False, null=True)),
                ('tftp_goahead', models.CharField(editable=False, max_length=50, null=True)),
                ('tftp_precheck_result', models.CharField(editable=False, max_length=5000, null=True)),
                ('tftp_device_status', models.CharField(editable=False, max_length=100, null=True)),
                ('tftp_image_upload_status', models.CharField(editable=False, max_length=50, null=True)),
                ('tftp_image_upload_log', models.CharField(editable=False, max_length=500, null=True)),
                ('tftp_image_upload_msg', models.CharField(editable=False, max_length=50, null=True)),
                ('tftp_image_available', models.CharField(editable=False, max_length=50, null=True)),
                ('validation_result', models.CharField(editable=False, max_length=50, null=True)),
                ('tftp_md5_match', models.CharField(editable=False, max_length=50, null=True)),
                ('comparediff', models.CharField(editable=False, max_length=10000, null=True)),
                ('tftp_cmd_result_data', models.CharField(editable=False, max_length=10000, null=True)),
            ],
        ),
    ]
