# Generated by Django 3.2.8 on 2022-01-04 10:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradedata',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='upgradedata',
            name='last_modified',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 4, 10, 31, 56, 73525, tzinfo=utc), editable=False, null=True),
        ),
    ]
