# Generated by Django 3.2.8 on 2022-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0002_auto_20220104_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upgradedata',
            name='last_modified',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
