# Generated by Django 3.2.8 on 2022-01-04 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0003_alter_upgradedata_last_modified'),
    ]

    operations = [
    ]
