# Generated by Django 3.2.8 on 2022-01-04 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0004_auto_20220104_1602'),
    ]

    operations = [
    ]
