# Generated by Django 3.2.8 on 2022-01-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0005_auto_20220104_1641'),
    ]

    operations = [
    ]
