# Generated by Django 3.2.8 on 2022-01-05 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cisco', '0009_auto_20220105_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upgradedata',
            name='device_free_space_post',
        ),
        migrations.RemoveField(
            model_name='upgradedata',
            name='tftp_cmd_result_data',
        ),
        migrations.RemoveField(
            model_name='upgradedata',
            name='tftp_image_size',
        ),
    ]
